language: go

go:
  - 1.11.x
  - master

env:
  - GIN_MODE="test" GO111MODULE=on

cache:
  directories:
    - ./vendor

before_install:
  - go mod tidy
  - go mod vendor
  - go get github.com/swaggo/swag/cmd/swag
  - swag init
  - go get -t ./...

script:
  - make cov

after_success:
  - bash < (curl -s https://codecov.io/bash)